import {ABILITIES,ENEMIES,ITEMS,QUESTS,SAVE_KEY,SAVE_VERSION,makeItem,initialState} from './data.js';

export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function roll(sides=20){return 1+Math.floor(Math.random()*sides)}
export function dice(expr){const m=String(expr).match(/^(\d+)d(\d+)(?:\s*([+-])\s*(\d+))?$/i);if(!m)return 0;let total=0;for(let i=0;i<+m[1];i++)total+=roll(+m[2]);const mod=m[4]?+m[4]*(m[3]==='-'?-1:1):0;return total+mod}
export function modifier(v){return Math.floor((v-10)/2)}
export function check(state,stat,dc){const r=roll(20),m=modifier(state.player.stats[stat]||0),lvl=Math.floor((state.player.level-1)/2),total=r+m+lvl;return {roll:r,modifier:m,levelBonus:lvl,total,dc,success:r===20||(r!==1&&total>=dc),critical:r===20,naturalOne:r===1}}
export function makeEngine(state,onEvent=()=>{}){
 const emit=(type,payload={})=>{state.history.push({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),turn:state.turn,type,payload,ts:Date.now()});state.history=state.history.slice(-250);state.meta.updatedAt=Date.now();onEvent(type,payload)};
 const xpNeeded=()=>100+((state.player.level-1)*60);
 function addXp(amount){state.player.xp+=amount;emit('XP_GAINED',{amount});while(state.player.xp>=xpNeeded()){state.player.xp-=xpNeeded();state.player.level++;state.player.maxHp+=5;state.player.maxMp+=2;state.player.hp=state.player.maxHp;state.player.mp=state.player.maxMp;emit('PLAYER_LEVEL_UP',{level:state.player.level})}}
 function addItem(id,qty=1){const found=state.player.inventory.find(i=>i.id===id);if(found)found.qty=(found.qty||1)+qty;else state.player.inventory.push(makeItem(id,qty));emit('ITEM_ACQUIRED',{id,qty});updateQuest('blacksmith','ore',id==='iron-ore'?qty:0)}
 function changeRep(faction,delta){if(!(faction in state.world.factions))state.world.factions[faction]=0;state.world.factions[faction]=clamp(state.world.factions[faction]+delta,-100,100);emit('FACTION_REPUTATION_CHANGED',{faction,delta,value:state.world.factions[faction]})}
 function updateQuest(qid,oid,delta=1){const q=state.quests.progress[qid];if(!q||!(oid in q)||delta<=0)return;q[oid]=clamp(q[oid]+delta,0,QUESTS[qid]?.objectives.find(o=>o.id===oid)?.required||999);emit('QUEST_PROGRESS',{questId:qid,objectiveId:oid,value:q[oid]});const def=QUESTS[qid];if(def&&def.objectives.every(o=>(q[o.id]||0)>=o.required)&&state.quests.active.includes(qid)){state.quests.active=state.quests.active.filter(x=>x!==qid);state.quests.completed.push(qid);addXp(def.reward.xp);state.player.gold+=def.reward.gold;emit('QUEST_COMPLETED',{questId:qid,reward:def.reward})}}
 function advance(hours=1){for(let i=0;i<hours;i++){state.turn++;if(state.turn%6===0){state.world.day++;state.world.threat=clamp(state.world.threat+1,0,10);emit('WORLD_DAY_ADVANCED',{day:state.world.day})}for(const c of state.player.conditions)c.turns--;state.player.conditions=state.player.conditions.filter(c=>c.turns>0);for(const n of Object.values(state.world.npcs))if(n.activity)n.activity=(n.activity+1)%4}emit('TURN_ADVANCED',{hours})}
 function damage(amount,source='unknown'){state.player.hp=clamp(state.player.hp-amount,0,state.player.maxHp);emit('PLAYER_DAMAGED',{amount,source,hp:state.player.hp});if(state.player.hp===0)defeat()}
 function heal(amount){state.player.hp=clamp(state.player.hp+amount,0,state.player.maxHp);emit('PLAYER_HEALED',{amount,hp:state.player.hp})}
 function useItem(id){const i=state.player.inventory.find(x=>x.id===id&&x.qty>0);if(!i)return false;if(i.type==='consumable'&&i.heal){heal(i.heal);i.qty--;emit('ITEM_USED',{id});return true}return false}
 function equip(id){const item=state.player.inventory.find(x=>x.id===id);if(!item||!item.slot)return false;const previous=state.player.equipment[item.slot];state.player.equipment[item.slot]=id;item.equipped=true;if(previous){const old=state.player.inventory.find(x=>x.id===previous);if(old)old.equipped=false}emit('ITEM_EQUIPPED',{id,slot:item.slot});return true}
 function defeat(){state.player.hp=Math.ceil(state.player.maxHp*.35);state.player.gold=Math.max(0,state.player.gold-5);state.world.threat=clamp(state.world.threat+2,0,10);emit('PLAYER_DEFEATED',{goldLost:5,recoveryHp:state.player.hp});updateQuest('crossroads','survive',1)}
 function startCombat(enemyId='revenant'){const e=ENEMIES[enemyId]||ENEMIES.revenant;state.pending={type:'combat',enemy:{...e,hp:e.hp,maxHp:e.hp},guard:0};emit('COMBAT_STARTED',{enemyId:e.id});return state.pending.enemy}
 function attack(abilityId='strike'){if(!state.pending||state.pending.type!=='combat')startCombat();const e=state.pending.enemy,a=ABILITIES[abilityId]||ABILITIES.strike;if(state.player.mp<a.cost)return {ok:false,reason:'Not enough resource'};state.player.mp-=a.cost;const stat=a.stat||'might',c=check(state,stat,e.dc);if(c.success){let amount=dice(a.dice||'1d6')+Math.max(0,modifier(state.player.stats[stat]||0));if(c.critical)amount*=2;amount=Math.max(1,amount-(e.armor||0));e.hp=clamp(e.hp-amount,0,e.maxHp);emit('DAMAGE_DEALT',{target:e.id,amount,critical:c.critical,roll:c});if(a.status)applyCondition(e,a.status,2);if(e.hp===0){const gold=roll(8);state.player.gold+=gold;addXp(e.xp);for(const id of e.loot||[])if(Math.random()<.55)addItem(id,1);emit('COMBAT_WON',{enemyId:e.id,gold});state.pending=null;updateQuest('crossroads','survive',1);return {ok:true,won:true,roll:c,amount}}}else{const taken=Math.max(1,roll(e.attack||4)-(state.pending.guard||0));damage(taken,e.name);emit('ENEMY_ATTACKED',{enemyId:e.id,amount:taken,roll:c})}advance();return {ok:true,roll:c,enemy:e}}
 function applyCondition(target,status,turns){if(target===state.player){const existing=state.player.conditions.find(c=>c.name===status);if(existing)existing.turns=Math.max(existing.turns,turns);else state.player.conditions.push({name:status,turns});emit('STATUS_APPLIED',{target:'player',status,turns})}else target.status=status}
 function guard(){if(state.player.mp<ABILITIES.guard.cost)return false;state.player.mp-=ABILITIES.guard.cost;if(state.pending)state.pending.guard=ABILITIES.guard.armor;emit('GUARD_RAISED',{armor:ABILITIES.guard.armor});advance();return true}
 function skill(stat,dc,context='general'){const c=check(state,stat,dc);emit('SKILL_CHECK',{stat,context,...c});advance();return c}
 function move(destination){state.location=destination;state.scene=`You arrive at ${destination}.`;state.world.threat=clamp(state.world.threat+(Math.random()<.2?1:0),0,10);emit('PLAYER_MOVED',{destination});advance();return true}
 function talk(npcId){const n=state.world.npcs[npcId]||(state.world.npcs[npcId]={id:npcId,name:npcId,trust:0,knowledge:[],activity:0,relationship:0});emit('NPC_INTERACTION',{npcId,trust:n.trust});updateQuest('blacksmith','talk',npcId==='blacksmith'?1:0);return n}
 function command(cmd){switch(cmd.type){case'MOVE':return move(cmd.destination);case'ATTACK':return attack(cmd.abilityId);case'GUARD':return guard();case'USE_ITEM':return useItem(cmd.itemId);case'EQUIP':return equip(cmd.itemId);case'TALK':return talk(cmd.npcId);case'CHECK':return skill(cmd.stat,cmd.dc,cmd.context);case'REST':state.player.hp=state.player.maxHp;state.player.mp=state.player.maxMp;emit('PLAYER_RESTED',{});advance(2);return true;default:emit('CUSTOM_COMMAND',{text:cmd.text||''});return true}}
 return {emit,addXp,addItem,changeRep,updateQuest,advance,damage,heal,useItem,equip,startCombat,attack,guard,skill,move,talk,command,xpNeeded};
}

export function migrate(raw){if(!raw||typeof raw!=='object')return null;if(raw.version===SAVE_VERSION)return raw;return null}
export function save(state){localStorage.setItem(SAVE_KEY,JSON.stringify(state));state.meta.updatedAt=Date.now()}
export function load(){try{return migrate(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'))}catch{return null}}
export function resetSave(){localStorage.removeItem(SAVE_KEY)}
export function commandFromText(text){const t=text.toLowerCase();if(/\b(rest|sleep|camp)\b/.test(t))return {type:'REST'};if(/\b(attack|fight|strike|hit)\b/.test(t))return {type:'ATTACK',abilityId:/fire|spell/.test(t)?'fireball':'strike'};if(/\b(guard|defend|block)\b/.test(t))return {type:'GUARD'};if(/\b(heal|potion|herb|tonic)\b/.test(t))return {type:'USE_ITEM',itemId:'moonleaf'};if(/\bblacksmith\b/.test(t))return {type:'TALK',npcId:'blacksmith'};return {type:'CUSTOM',text}}
