import {initialState,QUESTS,ITEMS} from './data.js';
import {makeEngine,save,load,commandFromText} from './engine.js';
import {director,fallback} from './ai.js';
import {createRenderer} from './renderer.js';
import {saveSlot,loadSlot} from './persistence.js';
import {createWorldSystems} from './systems.js';
import './selftest.js';

let state=load()||initialState();let engine;let systems;
const $=id=>document.getElementById(id);
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function eventText(type,p){const map={PLAYER_MOVED:`You travel to ${p.destination}.`,NPC_INTERACTION:`You interact with ${p.npcId}.`,DAMAGE_DEALT:`You deal ${p.amount} damage${p.critical?' — CRITICAL':''}.`,ENEMY_ATTACKED:`The enemy hits you for ${p.amount}.`,COMBAT_STARTED:`Combat begins against ${p.enemyId}.`,COMBAT_WON:`Victory. You gain ${p.gold} gold.`,PLAYER_DEFEATED:`Defeat. You recover, but lose ${p.goldLost} gold.`,ITEM_ACQUIRED:`You acquire ${p.id}${p.qty>1?' ×'+p.qty:''}.`,ITEM_USED:`You use ${p.id}.`,ITEM_EQUIPPED:`You equip ${p.id}.`,PLAYER_LEVEL_UP:`LEVEL UP — you are now level ${p.level}.`,QUEST_PROGRESS:`Quest progress updated.`,QUEST_COMPLETED:`QUEST COMPLETE — reward claimed.`,FACTION_REPUTATION_CHANGED:`${p.faction} reputation ${p.delta>=0?'+':''}${p.delta}.`,WORLD_DAY_ADVANCED:`A new day begins: ${p.day}.`,PLAYER_RESTED:'You rest and recover.',GUARD_RAISED:'You raise your guard.',NPC_RELATIONSHIP_CHANGED:`Your relationship with ${p.npcId} changes by ${p.delta}.`,NPC_MEMORY_CREATED:`A memory has been formed.`};return map[type]||null;}
function onEvent(type,p){const text=eventText(type,p);if(text)addFeed('SYSTEM',text);render();}
function boot(){engine=makeEngine(state,onEvent);systems=createWorldSystems(state,engine);bind();render();if(!state.history.some(x=>x.type==='FEED')){addFeed('NARRATOR','The violet sky hangs over the Whispering Crossroads. A bell rings once, though no bell tower stands nearby.');setChoices(['Investigate the strange omen','Approach the road','Prepare for danger']);persist()}}
function persist(){save(state);saveSlot('autosave',state).catch(()=>{})}
function addFeed(kind,text){state.history.push({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),turn:state.turn,type:'FEED',payload:{kind,text},ts:Date.now()});state.history=state.history.slice(-250);renderFeed()}
function renderFeed(){const rows=state.history.filter(x=>x.type==='FEED').slice(-80);$('feed').innerHTML=rows.map(x=>`<div class="entry"><div class="who">${esc(x.payload.kind)} · T${x.turn}</div><div class="body">${esc(x.payload.text)}</div></div>`).join('');$('feed').scrollTop=$('feed').scrollHeight}
function setChoices(items){$('choices').innerHTML=items.slice(0,3).map((x,i)=>`<button class="choice" data-choice="${i}">${esc(x)}</button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>act(b.textContent))}
function render(){const p=state.player,need=engine?engine.xpNeeded():100;$('loc').textContent=state.location;$('day').textContent=`DAY ${state.world.day} · T${state.turn}`;$('hero').textContent=`${p.name} · Lv ${p.level}`;$('hp').textContent=`${p.hp} / ${p.maxHp} HP`;$('mp').textContent=`${p.mp} / ${p.maxMp} MP`;$('xp').textContent=`${p.xp} / ${need} XP`;$('gold').textContent=p.gold;$('hpbar').style.width=`${p.hp/p.maxHp*100}%`;$('mpbar').style.width=`${p.mp/p.maxMp*100}%`;$('xpbar').style.width=`${p.xp/need*100}%`;$('stats').innerHTML=Object.entries(p.stats).map(([k,v])=>`<div class="stat"><small>${k}</small>${v}</div>`).join('');$('equip').innerHTML=Object.entries(p.equipment).map(([slot,id])=>`<div class="listrow"><span>${esc(slot)}</span><small>${id?esc(ITEMS[id]?.name||id):'—'}</small></div>`).join('');$('conditions').innerHTML=p.conditions.length?p.conditions.map(c=>`<span class="tag">${esc(c.name)} ${c.turns}</span>`).join(''):'<span class="muted">None</span>';$('inventory').innerHTML=p.inventory.map(i=>`<div class="listrow"><span>${i.equipped?'◆ ':''}${esc(i.name)} ×${i.qty||1}</span><small>${i.power?`ATK ${i.power}`:i.armor?`ARM ${i.armor}`:i.heal?`HEAL ${i.heal}`:i.type}</small></div>`).join('');$('quests').innerHTML=state.quests.active.map(id=>{const q=QUESTS[id],pr=state.quests.progress[id]||{};return `<div class="pad"><b>${esc(q.name)}</b><div class="muted">${esc(q.description)}</div>${q.objectives.map(o=>`<div class="listrow"><span>${esc(o.label)}</span><small>${pr[o.id]||0}/${o.required}</small></div>`).join('')}</div>`}).join('')||'<div class="pad muted">No active quests.</div>';$('world').innerHTML=`<div class="listrow"><span>Weather</span><b>${esc(state.world.weather)}</b></div><div class="listrow"><span>Threat</span><b>${state.world.threat}/10</b></div>${Object.entries(state.world.factions).map(([k,v])=>`<div class="listrow"><span>${esc(k)}</span><b class="${v<0?'bad':'good'}">${v>0?'+':''}${v}</b></div>`).join('')}<div class="heading">NPCs</div>${Object.values(state.world.npcs).map(n=>`<div class="listrow"><span>${esc(n.name)}</span><small>Trust ${n.trust||0} · Rel ${n.relationship||0}</small></div>`).join('')}`;$('audit').innerHTML=state.history.slice(-50).reverse().map(x=>`<div class="listrow"><span>${esc(x.type)}</span><small>T${x.turn}</small></div>`).join('');$('scene').textContent=state.scene;$('threat').textContent=`Threat ${state.world.threat}/10`;renderFeed()}
async function act(intent){intent=String(intent||'').trim();if(!intent)return;$('intent').value='';$('act').disabled=true;$('status').textContent='Resolving action…';const cmd=commandFromText(intent);if(cmd.type!=='CUSTOM'){if(cmd.type==='ATTACK'&&!state.pending)engine.startCombat(systems.encounter()||'revenant');const result=engine.command(cmd);if(cmd.type==='TALK'){systems.remember('blacksmith',`The player spoke with you on day ${state.world.day}.`,50);systems.relationship('blacksmith',2)}addFeed('PLAYER',intent);if(result?.won)addFeed('NARRATOR','The enemy falls. The realm remembers your victory.');setChoices(contextChoices());persist();$('status').textContent='Action resolved';$('act').disabled=false;return}addFeed('PLAYER',intent);let result;try{result=await director(intent,state)}catch(e){result=fallback(intent,state);$('status').textContent='AI unavailable — local narrative fallback'}state.ai.memory.push({role:'player',text:intent},{role:'narrator',text:result.narration});state.ai.memory=state.ai.memory.slice(-24);state.scene=result.narration;engine.advance();systems.simulate();addFeed('NARRATOR',result.narration);setChoices(result.choices);persist();render();$('status').textContent='Ready';$('act').disabled=false}
function contextChoices(){if(state.pending?.type==='combat')return ['Attack','Guard','Use a tonic'];if(state.world.threat>6)return ['Prepare for danger','Rest','Investigate'];return ['Investigate the strange omen','Talk to someone','Travel onward']}
function bind(){$('act').onclick=()=>act($('intent').value);$('intent').onkeydown=e=>{if(e.key==='Enter')act(e.target.value)};$('save').onclick=()=>{persist();$('status').textContent='Campaign saved'};$('load').onclick=async()=>{const s=await loadSlot('autosave')||load();if(s){state=s;engine=makeEngine(state,onEvent);systems=createWorldSystems(state,engine);render();addFeed('SYSTEM','Campaign loaded.')}};$('newCampaign').onclick=()=>$('modal').classList.add('open');$('closeModal').onclick=()=>$('modal').classList.remove('open');$('startCampaign').onclick=()=>{state=initialState($('charName').value,$('background').value);engine=makeEngine(state,onEvent);systems=createWorldSystems(state,engine);$('modal').classList.remove('open');render();addFeed('NARRATOR','A new campaign begins. Your choices will shape the world.');persist()};$('debug').onclick=()=>debugPanel();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('tab-'+b.dataset.tab).classList.add('active')})}
function debugPanel(){const recent=state.history.slice(-20).map(x=>`${x.turn} ${x.type} ${JSON.stringify(x.payload)}`).join('\n');alert(`DEBUG\nCampaign: ${state.campaignId}\nTurn: ${state.turn}\nAI memory: ${state.ai.memory.length}\nHistory: ${state.history.length}\nPending: ${state.pending?.type||'none'}\n\n${recent}`)}
createRenderer('game',state,cmd=>engine.command(cmd));boot();
