import {makeItem} from './data.js';
export function createWorldSystems(state,engine){
 const remember=(npcId,text,importance=50)=>{const n=state.world.npcs[npcId]||(state.world.npcs[npcId]={id:npcId,name:npcId,trust:0,relationship:0,knowledge:[],memories:[],activity:0});n.memories=n.memories||[];n.memories.push({text,importance,turn:state.turn});n.memories.sort((a,b)=>b.importance-a.importance||b.turn-a.turn);n.memories=n.memories.slice(0,20);n.knowledge=(n.knowledge||[]).slice(-8);if(importance>=60)n.knowledge.push(text);engine.emit('NPC_MEMORY_CREATED',{npcId,importance})};
 const relationship=(npcId,delta)=>{const n=state.world.npcs[npcId]||(state.world.npcs[npcId]={id:npcId,name:npcId,trust:0,relationship:0,knowledge:[],memories:[],activity:0});n.relationship=Math.max(-100,Math.min(100,(n.relationship||0)+delta));n.trust=Math.max(-100,Math.min(100,(n.trust||0)+Math.round(delta*.6)));engine.emit('NPC_RELATIONSHIP_CHANGED',{npcId,delta,value:n.relationship})};
 const craft=(recipe)=>{const recipes={iron_blade:{requires:{'iron-ore':3},result:'goblin-fang'}};const r=recipes[recipe];if(!r)return false;for(const [id,qty] of Object.entries(r.requires)){const item=state.player.inventory.find(i=>i.id===id);if(!item||item.qty<qty)return false}for(const [id,qty] of Object.entries(r.requires)){state.player.inventory.find(i=>i.id===id).qty-=qty}state.player.inventory.push({...makeItem(r.result),qty:1});engine.emit('ITEM_CRAFTED',{recipe,result:r.result});return true};
 const simulate=()=>{const roll=Math.random();if(roll<.15){state.world.threat=Math.min(10,state.world.threat+1);state.world.rumors.push(`Rumor from day ${state.world.day}: danger is spreading.`);state.world.rumors=state.world.rumors.slice(-10);engine.emit('WORLD_EVENT',{kind:'THREAT_RISE'})}else if(roll>.92){state.world.threat=Math.max(0,state.world.threat-1);engine.emit('WORLD_EVENT',{kind:'THREAT_FALL'})}Object.values(state.world.npcs).forEach(n=>{n.activity=(n.activity||0)+1;if(n.activity>3)n.activity=0})};
 const encounter=()=>{const t=state.world.threat+(state.player.level*.35);if(t>7)return 'warden';if(t>3)return Math.random()<.5?'goblin':'revenant';return Math.random()<.5?'goblin':null};
 return {remember,relationship,craft,simulate,encounter};
}
